### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by Evirtual** [noneedsystem/fucss#1]
For esample I need to put negative value to "left" property

**Comment by egislook** [comment]
so how we want to make it negative?

**Comment by egislook** [comment]
npx / npc / nem ?
n15px?
--15px?

**Comment by egislook** [comment]
im voting for --

**Comment by Evirtual** [comment]
I would even consider before value, use _ and than - fits right there nicely (e.g: mrg-l_-10px). You actually proposed this last time, I was doubting, but right now it seems ok.

**Comment by egislook** [comment]
So in other words we are spliting the value with _ everywhere then?

**Comment by egislook** [comment]
example bg-clr_fff

**Comment by egislook** [comment]
pdg_10px

**Comment by egislook** [comment]
mrg-l_-10px

**Comment by Evirtual** [comment]
Yep, I think that's a good aproach. Don't you think so?
