### ISSUE TITLE
bg + addon value is getting #

### ISSUE THREAD

**Issue by Evirtual** [noneedsystem/fucss#3]
I saw in code that in case of bg and clr value is getting #, but it also adds # if bg has, for example addon. I added sz (size) and after using bg-sz-cover, I'm getting background-size: #cover;

**Comment by egislook** [comment]
hm I think I can exclude bg cause practically this one should be bg-clr-fff for example

**Comment by Evirtual** [comment]
Yeah, I think if it has "clr" and it should only add # then. Good idea.

**Comment by Evirtual** [comment]
Also, at the same time you should add, that border-clr also adds #
